/* sch-pdf-compare core — the C ABI. GENERATED BY cbindgen, DO NOT EDIT.
 *
 * Regenerated by `cargo build -p sc-ffi`; CI fails if the committed copy and
 * the source disagree. Edit `crates/sc-ffi/src/lib.rs` instead.
 *
 * Copyright (c) the sch-pdf-compare authors. AGPL-3.0-or-later; see LICENSE.
 */

#ifndef SCHCOMPARE_H
#define SCHCOMPARE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Which of the three views a tile is composed for.
 */
enum ScViewMode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    SC_VIEW_MODE_OVERLAY = 0,
    SC_VIEW_MODE_ONLY_A = 1,
    SC_VIEW_MODE_ONLY_B = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ScViewMode ScViewMode;
#else
typedef uint8_t ScViewMode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Whether a piece of text was added, removed, or says something different.
 */
enum ScTextChangeKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * In the later revision only.
     */
    SC_TEXT_CHANGE_KIND_ADDED = 0,
    /**
     * In the earlier revision only.
     */
    SC_TEXT_CHANGE_KIND_REMOVED = 1,
    /**
     * In the same place on both, saying something different.
     */
    SC_TEXT_CHANGE_KIND_CHANGED = 2,
    /**
     * The same text, elsewhere on the sheet. Told apart from an addition and a
     * removal because a re-laid-out sheet moves dozens of identical labels and
     * reporting each twice buries the real changes.
     */
    SC_TEXT_CHANGE_KIND_MOVED = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ScTextChangeKind ScTextChangeKind;
#else
typedef uint8_t ScTextChangeKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * One open comparison. Opaque; every field is this crate's business.
 */
typedef struct ScSession ScSession;

/**
 * Which sheet of each document a virtual page stands for. 0 means the document
 * has no matching sheet, and that page is drawn as entirely added or removed.
 */
typedef struct {
    int32_t page_a;
    int32_t page_b;
} ScPair;

/**
 * 0 is success. Every failure is negative, so `if (status < 0)` is the whole
 * check a caller needs.
 */
typedef int32_t ScStatus;

/**
 * A composed tile, 32bpp BGRA, tightly packed.
 *
 * On a little-endian host this is exactly `QImage::Format_RGB32`, so the shell
 * wraps `pixels` without copying anything.
 */
typedef struct {
    const uint8_t *pixels;
    int32_t width;
    int32_t height;
    size_t stride;
} ScTile;

/**
 * A rectangle in page space, in points.
 */
typedef struct {
    float x;
    float y;
    float dx;
    float dy;
} ScRectF;

/**
 * How the sweep is getting on.
 *
 * `finished` is the only field that makes `changed_sheets` mean anything;
 * before that it is a running total.
 */
typedef struct {
    bool running;
    bool finished;
    int32_t scanned;
    int32_t total;
    int32_t changed_sheets;
    /**
     * Regions that recur across the set, waiting to be offered. Only ever
     * meaningful once `finished`.
     */
    int32_t suggested;
} ScSweepStatus;

/**
 * One difference in what the two revisions of a sheet say.
 */
typedef struct {
    ScTextChangeKind kind;
    /**
     * What the earlier revision said; an empty string for an addition.
     */
    const char *before;
    /**
     * What the later one says; an empty string for a removal.
     */
    const char *after;
    /**
     * Where it is, in page points.
     */
    ScRectF rect;
} ScTextChange;

#define SC_OK 0

/**
 * The render or scan has been started but has not finished; ask again when the
 * wakeup handle fires.
 */
#define SC_PENDING 1

#define SC_ERR_INVALID -1

#define SC_ERR_IO -2

#define SC_ERR_FORMAT -3

#define SC_ERR_NO_PAGE -4

#define SC_ERR_GEOMETRY -5

/**
 * The file is a PDF, but encrypted and we have no password for it.
 */
#define SC_ERR_LOCKED -6

/**
 * The file opened and has no pages — usually truncated or half-downloaded.
 */
#define SC_ERR_EMPTY -7

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The last failure on this thread, as a NUL-terminated string.
 *
 * # Safety
 * The pointer is valid until the next failing call on the same thread. Copy it
 * if you intend to keep it. Never null; an empty string means nothing has
 * failed yet.
 */
const char *sc_last_error(void);

/**
 * The library version, as a NUL-terminated string that lives forever.
 *
 * # Safety
 * Callable with no preconditions. The returned pointer is valid for the
 * lifetime of the process and must not be freed.
 */
const char *sc_version(void);

/**
 * Opens two revisions for comparison.
 *
 * # Safety
 * `path_a` and `path_b` must be NUL-terminated UTF-8. Returns null on failure,
 * with the reason in [`sc_last_error`]. Free with [`sc_session_free`].
 */
ScSession *sc_session_open(const char *path_a,
                           const char *path_b);

/**
 * Closes a comparison. Null is a no-op, and every pointer this session ever
 * handed out is dangling afterwards.
 *
 * # Safety
 * `s` must be a pointer from [`sc_session_open`] that has not already been
 * freed.
 */
void sc_session_free(ScSession *s);

/**
 * How many virtual sheets the comparison has.
 *
 * Not either document's own count: the range has to cover both, so a set that
 * gained sheets at the front is longer than either. 0 for a null session.
 *
 * # Safety
 * `s` must be null or a live session.
 */
int32_t sc_session_page_count(const ScSession *s);

/**
 * Which sheet of each document virtual page `page_no` stands for.
 *
 * # Safety
 * `s` must be null or a live session. A null session or an out-of-range page
 * gives `{0, 0}`.
 */
ScPair sc_session_pair(const ScSession *s, int32_t page_no);

/**
 * The sheet's size in points, after any rotation the file carries.
 *
 * # Safety
 * `s` must be null or a live session; `w_pt` and `h_pt` must be writable.
 */
ScStatus sc_session_page_size(const ScSession *s,
                              int32_t page_no,
                              float *w_pt,
                              float *h_pt);

/**
 * The sheet's size in device pixels at `zoom`, as the renderer will round it.
 *
 * The viewer lays pages out with this before it has rendered any of them.
 *
 * # Safety
 * `s` must be null or a live session; `w` and `h` must be writable.
 */
ScStatus sc_session_page_device_size(const ScSession *s,
                                     int32_t page_no,
                                     float zoom,
                                     int32_t *w,
                                     int32_t *h);

/**
 * Composes a tile of the comparison.
 *
 * `x` and `y` are device pixels at `zoom` with their origin at the sheet's
 * top-left. `mode` is per tile rather than taken from the session, because a
 * side-by-side view wants both single-document views on screen at once.
 *
 * # Safety
 * `s` must be a live session and `out` writable. **The pixels `out` points at
 * are borrowed and stay valid only until the next `sc_session_tile` call on
 * this session, or until it is freed.** Draw from them or copy them; do not
 * keep the pointer.
 */
ScStatus sc_session_tile(ScSession *s,
                         int32_t page_no,
                         float zoom,
                         int32_t x,
                         int32_t y,
                         int32_t width,
                         int32_t height,
                         ScViewMode mode,
                         ScTile *out);

/**
 * # Safety
 * `s` must be null or a live session.
 */
ScViewMode sc_session_view_mode(const ScSession *s);

/**
 * # Safety
 * `s` must be null or a live session.
 */
void sc_session_set_view_mode(ScSession *s, ScViewMode mode);

/**
 * The largest tolerance the core will accept.
 *
 * Asked for rather than written into the frontend: the ceiling is a property
 * of the comparison kernel and has moved once already, and a spin box that
 * stops one short of what the core allows is a control that lies.
 *
 * # Safety
 * Callable with no preconditions.
 */
int32_t sc_max_tolerance(void);

/**
 * The tolerance past which small movements stop being reported.
 *
 * Not a limit — a line to tell the reader they have crossed. Above it the
 * slack is wider than a component that shifted slightly, so such a shift reads
 * as no change at all, and nothing else on screen would say so.
 *
 * # Safety
 * Callable with no preconditions.
 */
int32_t sc_tolerance_hides_movement(void);

/**
 * How far, in device pixels, ink may sit from its counterpart and still count
 * as the same artwork. Clamped to `0..=sc_max_tolerance()`.
 *
 * # Safety
 * `s` must be null or a live session.
 */
int32_t sc_session_tolerance(const ScSession *s);

/**
 * Changing the tolerance changes every answer, so the scan cache is dropped.
 *
 * # Safety
 * `s` must be null or a live session.
 */
void sc_session_set_tolerance(ScSession *s, int32_t tolerance);

/**
 * How strongly the overlay draws the artwork the two revisions agree on, 0 to
 * 100.
 *
 * 100 is the drawing as it was drawn, with the changes coloured on top. Lower
 * fades the agreed ink towards white and leaves the differences at full
 * strength, so at 0 the sheet is blank except for exactly what changed — which
 * is how three small edits are found on a sheet of dense line work.
 *
 * # Safety
 * `s` must be null or a live session.
 */
int32_t sc_session_shared_ink(const ScSession *s);

/**
 * Clamped to 0..=100.
 *
 * Every composed tile is drawn from this, so the cached ones are dropped. The
 * scans are not: this changes how the comparison is painted, never what it
 * found. A reader who fades the drawing away must still be told the same
 * number of sheets changed.
 *
 * # Safety
 * `s` must be null or a live session.
 */
void sc_session_set_shared_ink(ScSession *s, int32_t percent);

/**
 * # Safety
 * `s` must be null or a live session.
 */
int32_t sc_session_page_delta(const ScSession *s);

/**
 * The two overlay colours, packed as `0x00RRGGBB`.
 *
 * Configurable because the default pair is red and green, and a reader with
 * red-green colour blindness cannot use it. Everything this tool shows is
 * carried by those two colours, so this is not a preference.
 *
 * # Safety
 * `s` must be null or a live session; `only_a` and `only_b` must be writable.
 */
ScStatus sc_session_colours(const ScSession *s,
                            uint32_t *only_a,
                            uint32_t *only_b);

/**
 * Sets the two overlay colours, packed as `0x00RRGGBB`.
 *
 * Every composed tile is drawn from these, so the cached ones are dropped. The
 * scans are not: which regions differ does not depend on how they are painted.
 *
 * # Safety
 * `s` must be null or a live session.
 */
void sc_session_set_colours(ScSession *s,
                            uint32_t only_a,
                            uint32_t only_b);

/**
 * Nudges which sheet of B lines up with which sheet of A.
 *
 * Every cached scan is about the old pairing, so they all go.
 *
 * # Safety
 * `s` must be null or a live session.
 */
void sc_session_set_page_delta(ScSession *s, int32_t delta);

/**
 * Works out which sheet of B each sheet of A corresponds to, from what is
 * written on them, and uses that as the pairing.
 *
 * For a set that simply gained a sheet at the front, [`sc_session_set_page_delta`]
 * does the same job and is more predictable. This is for the case an offset
 * cannot express: sheets reordered, or inserted in the middle. It replaces any
 * delta, and every cached answer with it.
 *
 * # Safety
 * `s` must be null or a live session.
 */
ScStatus sc_session_auto_match(ScSession *s);

/**
 * True when the pairing came from the documents rather than from an offset.
 *
 * # Safety
 * `s` must be null or a live session.
 */
bool sc_session_pairing_is_automatic(const ScSession *s);

/**
 * Excludes a region, in page points, from the comparison on **every** sheet —
 * which is what a shared title block needs.
 *
 * # Safety
 * `s` must be null or a live session.
 */
void sc_session_add_ignore_rect(ScSession *s,
                                float x,
                                float y,
                                float dx,
                                float dy);

/**
 * # Safety
 * `s` must be null or a live session.
 */
void sc_session_clear_ignore_rects(ScSession *s);

/**
 * # Safety
 * `s` must be null or a live session.
 */
size_t sc_session_ignore_rect_count(const ScSession *s);

/**
 * # Safety
 * `s` must be null or a live session; `out` must be writable.
 */
ScStatus sc_session_ignore_rect(const ScSession *s,
                                size_t index,
                                ScRectF *out);

/**
 * Scans one sheet for regions where the two documents disagree, and caches it.
 *
 * Costs roughly a third of a second the first time and nothing afterwards.
 *
 * # Safety
 * `s` must be null or a live session.
 */
ScStatus sc_session_scan_page(ScSession *s,
                              int32_t page_no);

/**
 * How many change regions the sheet's scan found. −1 if it has not been
 * scanned yet, which is not the same as 0.
 *
 * # Safety
 * `s` must be null or a live session.
 */
int32_t sc_session_change_count(const ScSession *s, int32_t page_no);

/**
 * How many of the sheet's regions fell inside an excluded rectangle.
 *
 * Reported rather than dropped: "not compared" must never read as "nothing
 * changed here".
 *
 * # Safety
 * `s` must be null or a live session.
 */
int32_t sc_session_ignored_count(const ScSession *s, int32_t page_no);

/**
 * Whether the two sheets of this pair are the same size on paper.
 *
 * 1 when they differ, 0 when they agree, −1 when the sheet has not been
 * scanned. A pair that differs is laid out to the first document's geometry and
 * the second is cropped, so the count of regions means nothing — which is worse
 * than a large count, because a small one reads as a nearly unchanged sheet.
 *
 * # Safety
 * `s` must be null or a live session.
 */
int32_t sc_session_size_mismatch(const ScSession *s,
                                 int32_t page_no);

/**
 * How much of the sheet the change regions cover, from 0 to 1. Negative when
 * the sheet has not been scanned.
 *
 * The count of regions cannot tell a few small edits from a sheet that differs
 * everywhere, because the clustering bridges neighbouring cells on purpose.
 *
 * # Safety
 * `s` must be null or a live session.
 */
float sc_session_coverage(const ScSession *s,
                          int32_t page_no);

/**
 * One change region, in page points.
 *
 * # Safety
 * `s` must be null or a live session; `out` must be writable.
 */
ScStatus sc_session_change(const ScSession *s,
                           int32_t page_no,
                           size_t index,
                           ScRectF *out);

/**
 * Starts scanning every sheet on a worker thread.
 *
 * The frontend should watch [`sc_session_wakeup_handle`] and call
 * [`sc_session_pump`] when it signals. Nothing is ever called back on the
 * worker thread.
 *
 * # Safety
 * `s` must be null or a live session.
 */
ScStatus sc_session_start_sweep(ScSession *s);

/**
 * Stops the sweep and waits for its thread. Safe to call when none is running.
 *
 * # Safety
 * `s` must be null or a live session.
 */
void sc_session_stop_sweep(ScSession *s);

/**
 * The handle to watch: a file descriptor on Unix, an event handle on Windows.
 *
 * −1 when no sweep is running. Valid only until the sweep is stopped or the
 * session is freed, so a frontend must drop its notifier before either.
 *
 * # Safety
 * `s` must be null or a live session.
 */
int64_t sc_session_wakeup_handle(const ScSession *s);

/**
 * Collects whatever the sweep has finished and clears the wakeup.
 *
 * Call this when the handle signals, and once more after `finished` shows up
 * so the last sheets are collected. Doing the work here, on the caller's
 * thread, is the point: the sweep never touches the frontend's data.
 *
 * # Safety
 * `s` must be null or a live session.
 */
ScStatus sc_session_pump(ScSession *s);

/**
 * # Safety
 * `s` must be null or a live session; `out` must be writable.
 */
ScStatus sc_session_sweep_status(const ScSession *s, ScSweepStatus *out);

/**
 * How many recurring regions the finished sweep would offer to exclude.
 *
 * Offered, never applied: a net renamed across the whole set looks exactly like
 * a changed title-block date, and hiding that silently is the worst failure
 * this tool could have.
 *
 * # Safety
 * `s` must be null or a live session.
 */
int32_t sc_session_suggested_count(const ScSession *s);

/**
 * # Safety
 * `s` must be null or a live session; `out` must be writable.
 */
ScStatus sc_session_suggested(const ScSession *s, size_t index, ScRectF *out);

/**
 * Puts the settings in `dir` rather than in the platform's own place.
 *
 * Pass null to go back to the platform's. A test uses this to write somewhere
 * harmless, and a portable installation to keep its settings beside itself.
 * Doing the same with an environment variable would mean knowing which one the
 * platform reads and trusting the frontend's way of setting it to reach this
 * process — neither of which held.
 *
 * # Safety
 * `dir` must be null or a NUL-terminated UTF-8 path.
 */
void sc_settings_set_dir(const char *dir);

/**
 * Where the settings are read from and written to.
 *
 * Empty when the platform says nothing about where they should go, in which
 * case nothing is saved. The string is borrowed and valid until the next call
 * to this function on the same thread.
 *
 * # Safety
 * Callable with no preconditions.
 */
const char *sc_settings_path(void);

/**
 * Loads this pair's saved state: the excluded regions worked out for it last
 * time, and the tolerance and colours in force.
 *
 * The frontend chooses whether to call this. A run started `-for-testing`
 * simply does not, which is how persistence is exercised without it.
 *
 * # Safety
 * `s` must be null or a live session.
 */
ScStatus sc_session_load_settings(ScSession *s);

/**
 * Saves this pair's excluded regions, and the tolerance and colours, for next
 * time.
 *
 * The file is re-read first, so a second window comparing a different pair does
 * not lose what it saved.
 *
 * # Safety
 * `s` must be null or a live session.
 */
ScStatus sc_session_save_settings(const ScSession *s);

/**
 * The pair compared most recently, for offering to reopen it.
 *
 * False when there is none. The strings are borrowed and valid until the next
 * call to this function on the same thread.
 *
 * # Safety
 * `path_a` and `path_b` must be writable, or null if that side is not wanted.
 */
bool sc_last_pair(const char **path_a, const char **path_b);

/**
 * The comparison as a document, in Markdown.
 *
 * Built from the sheets already scanned — it renders nothing, so a menu item
 * wired to this does not appear to hang. A sweep that has not finished is
 * reported honestly in the text rather than quietly producing a short answer.
 *
 * # Safety
 * `s` must be null or a live session. **The string is borrowed and stays valid
 * only until the next `sc_session_report` call on this session, or until it is
 * freed.** Null on failure.
 */
const char *sc_session_report(ScSession *s);

/**
 * Works out what the two revisions of this sheet say differently, and returns
 * how many differences there are.
 *
 * Negative on failure. Read them with [`sc_session_text_change`].
 *
 * This complements the overlay rather than replacing it — the overlay finds a
 * re-routed wire that carries no text at all. It is, though, the answer to the
 * case the overlay handles worst: when two revisions went through different PDF
 * producers every glyph is drawn differently and the overlay reports about
 * twenty-five regions a sheet, while the words report the two that changed.
 *
 * # Safety
 * `s` must be null or a live session.
 */
int32_t sc_session_text_changes(ScSession *s,
                                int32_t page_no);

/**
 * One of the differences found by the last [`sc_session_text_changes`] call.
 *
 * # Safety
 * `s` must be null or a live session and `out` writable. **The strings `out`
 * points at are borrowed and stay valid only until the next
 * `sc_session_text_changes` call on this session, or until it is freed.**
 */
ScStatus sc_session_text_change(const ScSession *s,
                                size_t index,
                                ScTextChange *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCHCOMPARE_H */
