/* sch-pdf-compare core — the C ABI. GENERATED BY cbindgen, DO NOT EDIT.
 *
 * Regenerated by `cargo build -p sc-ffi`; CI fails if the committed copy and
 * the source disagree. Edit `crates/sc-ffi/src/lib.rs` instead.
 *
 * Copyright (c) the sch-pdf-compare authors. AGPL-3.0-or-later; see LICENSE.
 */

#ifndef SCHCOMPARE_H
#define SCHCOMPARE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * 0 is success. Every failure is negative, so `if (status < 0)` is the whole
 * check a caller needs.
 */
typedef int32_t ScStatus;

#define SC_OK 0

/**
 * The render or scan has been started but has not finished; ask again when the
 * wakeup handle fires.
 */
#define SC_PENDING 1

#define SC_ERR_INVALID -1

#define SC_ERR_IO -2

#define SC_ERR_FORMAT -3

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The library version, as a NUL-terminated string that lives forever.
 *
 * # Safety
 * Callable with no preconditions. The returned pointer is valid for the
 * lifetime of the process and must not be freed.
 */
const char *sc_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCHCOMPARE_H */
